version: '24'

services:
  

  flask-app:
    build: .
    depends_on:
      - postgres
    environment:
     STAGE: test
     SQLALCHEMY_DATABASE_URI: postgresql://postgres:database-password@localhost:5432/postgres
    networks:
      - default
    ports:
      - 8080:8080
    volumes:
      - ./app:/usr/src/app/app
      - ./migrations:/usr/src/app/migrations
    restart: always
    # Other Flask app configuration options
  
  postgres:
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: database-password
      POSTGRES_DB: postgres
    image: postgres:latest
    networks:
      - default
    ports:
      - 5432:5432
    restart: always
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    # Other PostgreSQL configuration options