version: '24'

services:
  flaskapp:
    image: flaskapp
    build: .
    depends_on:
      - postgres
    environment:
     STAGE: test
     SQLALCHEMY_DATABASE_URI: postgresql://postgres:database-password@localhost:5432/postgres
    networks:
      - default
    ports:
      - 8080:8080
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: database-password
      POSTGRES_DB: postgres
    networks:
      - default
    ports:
      - 5432:5432
    
    # Other PostgreSQL configuration options